### PR TITLE
Package: Contentful Core

### PR DESCRIPTION
**Pull request by ryanhefner**
**Checklist**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

**Please check if the PR fulfills these requirements**

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Storybook or docs have been added / updated (for bug fixes / features)

**What is the ticket / issue associated with this change?** (Link to the ticket or issue)

#37 

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Move from using `@cmpsr/contentful` package to a combination of `@cmpsr/contentful-core` and `@cmpsr/contentful-components` (coming soon) to achieve the same results of that previous package.

### CODE REVIEW

**Comment by ryanhefner** [comment]
Just realized I should probably add some examples of using the `renderers` to the `README`.

Also, is there a good spot we should be putting examples? I have a Next example setup for this one, but was running into issues having it inside the monorepo because some of the package management was messed up due to the workspaces that Lerna uses to manage all that stuff.

**Comment by stevejcox** [comment]
> Just realized I should probably add some examples of using the `renderers` to the `README`.
> 
> Also, is there a good spot we should be putting examples? I have a Next example setup for this one, but was running into issues having it inside the monorepo because some of the package management was messed up due to the workspaces that Lerna uses to manage all that stuff. I was thinking maybe we could create a `composer-examples` repo or something.

Yeah, `examples` would be great! A nice long collection of examples over time will be super valuable.

**Comment by stevejcox** [comment]
This looks great! Can you run `changeset` to automate the publish of the new package?

So excited to get this in, thanks @ryanhefner !

**Comment by ryanhefner** [comment]
@stevejcox Should I do a major bump on all packages, or just `contentful-core`? Not sure what the best practices are when it comes to monorepos.

**Pull request merged**
