### PR TITLE
COM-426: Add figma addon to storybook and configure the button stories for tes…

### PR DESCRIPTION
**Pull request by TheEnmanuel23**
…ting purposes

## Please delete checklist items and sections that are not relevant

**Checklist**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Please check if the PR fulfills these requirements**

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Storybook or docs have been added / updated (for bug fixes / features)

**What is the ticket / issue associated with this change?** (Link to the ticket or issue)
https://impulsumvc.atlassian.net/browse/COM-426

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

**Storybook Link** (Link to a local storybook url to review new functionality)
https://5eed577398d08d0022b52d76-wifsjtbpdq.chromatic.com/?path=/story/components-primitives-button--all

### CODE REVIEW

**Review by TheEnmanuel23 — COMMENTED** [review]
[This library](https://storybook.js.org/addons/storybook-figma) is using a legacy version of storybook, a better option is [Designs Addon | Storybook](https://storybook.js.org/addons/storybook-addon-designs/)  it is pretty easy to implement, but we will need to edit each story in order to add the figma design link per component. 

You can see it working here with the `Button` component for testing purposes: https://5eed577398d08d0022b52d76-fkjqshnenb.chromatic.com/?path=/story/components-primitives-button--all (Click on the design tab)

**Review by tkanzakic — COMMENTED** [review]
Looking good so far. We need to link all components

**Review by TheEnmanuel23 — COMMENTED** [review]
These components don't have a figma link:

- icon
- modal
- numberedList
- none of the layout section
- And the  figma links associated to blocks section show me a `not found` message

**Comment by guilean** [comment]
> These components don't have a figma link:
> 
> * icon
> * modal
> * numberedList
> * none of the layout section
> * And the  figma links associated to blocks section show me a `not found` message

[Icons figma](https://www.figma.com/file/EVqzz5IwHOADFvr5yYhgvO/Composer---Icons-%26-Illustrations-(Community)?node-id=2%3A5)
[Modal and blocks figma](https://www.figma.com/file/8W5cS9BvZWevVAthkIsIRc/Composer----Blocks-(Community)?node-id=2%3A17)

About List, I believe design have to update the DSM.

**Comment by tkanzakic** [comment]
after discussing this does not add any real value, closing the pull request

**Pull request closed without merging**
